'\" t
.\" (The preceding line is a note to broken versions of man to tell
.\" them to pre-process this man page with tbl)
.\" Man page for pmap.
.\" Licensed under version 2 of the GNU General Public License.
.\" Written by Albert Cahalan.
.\"
.TH radiorecorder "1" "November 2017"
.SH NAME
radiorecorder \- record or play internet radio streams
.SH SYNOPSIS
.B radiorecorder
[\fIoptions\fR] \fIname-or-url\fR [...]
.SH DESCRIPTION
The radiorecorder command consumes one or more internet radio
streams and either records them to files, plays them locally
or using a Chromecast device.
.SH OPTIONS
.TP
\fBname-or-url\fR
Specifies the internet radio station(s) to use. Can either be the
name of a internet radio station as it can be found on the service
<http://www.radio-browser.info/> or an URL of a internet radio station
stream.
.TP
\fB\-c\fR, \fB\-cast\fR \fIcast-device\fR
Play the internet radio stream on the named
.I cast-device.
A list of available Chromecast devices can be retrieved with the \fB-L\fR option.
.TP
\fB\-d\fR, \fB\-directory\fR \fIdirectory\fR
Specifies the target
.I directory
to write the streams to.
.TP
\fB\-h\fR, \fB\-help\fR
Show the command line help of the program.
.TP
\fB\-L\fR, \fB\-list\-cast\fR
Lists the available Chromecast devices. Will listen to new Chromecast devices
until interruption. Needs to be interrupted with CTRL-C.
.TP
\fB\-M\fR, \fB\-min\-free\fR \fImegs\fR
Keep the given number of
.I megs
mega bytes of disk space free. Defaults to 512.
.TP
\fB\-p\fR, \fB\-play\fR
Plays the stream to the local audio facility using Java Media Framework.
You can listen to music on your computer with this option. Note that
this program is not designed to be a music player.
.TP
\fB\-r\fR, \fB\-reconnect\fR
Automatically reconnect after connection loss.
.TP
\fB\-t\fR, \fB\-timeout\fR \fIsecs\fR
Connect or read timeout in seconds.
.TP
\fB\-S\fR, \fB\-use\-songnames\fR
Use the song names that were eventually sent in the stream and name
the output files according to the retrieved song names.

.SH COPYRIGHT
Copyright \(co 2017 Stephan Fuhrmann

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
.br
    <http://www.apache.org/licenses/LICENSE-2.0>
.br
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. 
.SH "REPORTING BUGS"
Please file an issue at: <https://github.com/sfuhrm/radiorecorder/issues>
.SH "SEE ALSO"
The project lives at: <https://github.com/sfuhrm/radiorecorder>

