

name: JPackage

on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:       # manual start via UI

jobs:
  maven_version:
    uses: sfuhrm/github_workflows/.github/workflows/maven-expression.yml@main
    permissions:
      contents: read
    with:
      java_version: 21
      expression: project.version
  jpackage:
    needs:
      - maven_version
    permissions:
      contents: read
    uses: sfuhrm/github_workflows/.github/workflows/jpackage.yml@main
    with:
      java_version: 21
      artifact_name: jpackage
      jpackage_input: radiorecorder/target/radiorecorder-${{ needs.maven_version.outputs.expression_value }}-app/radiorecorder-${{ needs.maven_version.outputs.expression_value }}
      jpackage_name: radiorecorder
      jpackage_jarfile: lib/radiorecorder-${{ needs.maven_version.outputs.expression_value }}.jar
      jpackage_license: radiorecorder/target/radiorecorder-${{ needs.maven_version.outputs.expression_value }}-app/radiorecorder-${{ needs.maven_version.outputs.expression_value }}/LICENSE
      jpackage_vendor: Stephan Fuhrmann
      jpackage_copyright: Stephan Fuhrmann
      jpackage_description: Records and plays internet radio streams
      jpackage_mainclass: de.sfuhrm.radiorecorder.Main
      jpackage_linux_deb_maintainer: s@sfuhrm.de
      jpackage_linux_deb_app_category: gnome
      jpackage_linux_rpm_app_category: utilities
      jpackage_win_upgrade_uuid: a32f7c72-87d5-44ab-91b6-1f4e13fea46b
  binary-archives:
    needs: maven_version
    uses: sfuhrm/github_workflows/.github/workflows/maven.yml@main
    permissions:
      contents: read
    with:
      java_version: "[ \"21\" ]"
      artifact_name: binaries
      artifact_path: radiorecorder/target/radiorecorder-${{ needs.maven_version.outputs.expression_value }}-bin.*
  merge-and-sign-archives:
    needs:
      - jpackage
      - binary-archives
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Download package jpackages
        uses: actions/download-artifact@v4.1.7
        with:
          path: merge
          pattern: jpackage
          merge-multiple: true
      - name: Download package platform neutral binaries
        uses: actions/download-artifact@v4.1.7
        with:
          path: merge
          pattern: binaries*
          merge-multiple: true
      - name: GPG-sign files
        uses: sfuhrm/gpg-sign-action@main
        with:
          path: merge
          gpg-key: "${{ secrets.GPG_KEYFILE }}"
          gpg-passphrase: "${{ secrets.GPG_PASSPHRASE }}"
      - uses: actions/upload-artifact@v4
        with:
          name: all
          path: merge
